/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LineasRouteImport } from './routes/lineas'
import { Route as IntegrantesRouteImport } from './routes/integrantes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyUpdatesRouteImport } from './routes/_authenticated/weekly-updates'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardStudentRouteImport } from './routes/_authenticated/dashboard.student'
import { Route as AuthenticatedDashboardCoordinatorRouteImport } from './routes/_authenticated/dashboard.coordinator'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard.admin.index'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard.admin.users'
import { Route as AuthenticatedDashboardAdminStudentsRouteImport } from './routes/_authenticated/dashboard.admin.students'
import { Route as AuthenticatedDashboardAdminProjectsRouteImport } from './routes/_authenticated/dashboard.admin.projects'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LineasRoute = LineasRouteImport.update({
  id: '/lineas',
  path: '/lineas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrantesRoute = IntegrantesRouteImport.update({
  id: '/integrantes',
  path: '/integrantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyUpdatesRoute =
  AuthenticatedWeeklyUpdatesRouteImport.update({
    id: '/weekly-updates',
    path: '/weekly-updates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentRoute =
  AuthenticatedDashboardStudentRouteImport.update({
    id: '/dashboard/student',
    path: '/dashboard/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCoordinatorRoute =
  AuthenticatedDashboardCoordinatorRouteImport.update({
    id: '/dashboard/coordinator',
    path: '/dashboard/coordinator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminStudentsRoute =
  AuthenticatedDashboardAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminProjectsRoute =
  AuthenticatedDashboardAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/integrantes': typeof IntegrantesRoute
  '/lineas': typeof LineasRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre': typeof SobreRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/weekly-updates': typeof AuthenticatedWeeklyUpdatesRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/dashboard/coordinator': typeof AuthenticatedDashboardCoordinatorRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/projects': typeof AuthenticatedDashboardAdminProjectsRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/integrantes': typeof IntegrantesRoute
  '/lineas': typeof LineasRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre': typeof SobreRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/weekly-updates': typeof AuthenticatedWeeklyUpdatesRoute
  '/dashboard/coordinator': typeof AuthenticatedDashboardCoordinatorRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/projects': typeof AuthenticatedDashboardAdminProjectsRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/integrantes': typeof IntegrantesRoute
  '/lineas': typeof LineasRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/weekly-updates': typeof AuthenticatedWeeklyUpdatesRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/_authenticated/dashboard/coordinator': typeof AuthenticatedDashboardCoordinatorRoute
  '/_authenticated/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/projects': typeof AuthenticatedDashboardAdminProjectsRoute
  '/_authenticated/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/contacto'
    | '/integrantes'
    | '/lineas'
    | '/login'
    | '/proyectos'
    | '/sobre'
    | '/resources'
    | '/weekly-updates'
    | '/dashboard/admin'
    | '/dashboard/coordinator'
    | '/dashboard/student'
    | '/dashboard/'
    | '/dashboard/admin/projects'
    | '/dashboard/admin/students'
    | '/dashboard/admin/users'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/contacto'
    | '/integrantes'
    | '/lineas'
    | '/login'
    | '/proyectos'
    | '/sobre'
    | '/resources'
    | '/weekly-updates'
    | '/dashboard/coordinator'
    | '/dashboard/student'
    | '/dashboard'
    | '/dashboard/admin/projects'
    | '/dashboard/admin/students'
    | '/dashboard/admin/users'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/actividades'
    | '/contacto'
    | '/integrantes'
    | '/lineas'
    | '/login'
    | '/proyectos'
    | '/sobre'
    | '/_authenticated/resources'
    | '/_authenticated/weekly-updates'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/coordinator'
    | '/_authenticated/dashboard/student'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/projects'
    | '/_authenticated/dashboard/admin/students'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActividadesRoute: typeof ActividadesRoute
  ContactoRoute: typeof ContactoRoute
  IntegrantesRoute: typeof IntegrantesRoute
  LineasRoute: typeof LineasRoute
  LoginRoute: typeof LoginRoute
  ProyectosRoute: typeof ProyectosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineas': {
      id: '/lineas'
      path: '/lineas'
      fullPath: '/lineas'
      preLoaderRoute: typeof LineasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrantes': {
      id: '/integrantes'
      path: '/integrantes'
      fullPath: '/integrantes'
      preLoaderRoute: typeof IntegrantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-updates': {
      id: '/_authenticated/weekly-updates'
      path: '/weekly-updates'
      fullPath: '/weekly-updates'
      preLoaderRoute: typeof AuthenticatedWeeklyUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student': {
      id: '/_authenticated/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthenticatedDashboardStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/coordinator': {
      id: '/_authenticated/dashboard/coordinator'
      path: '/dashboard/coordinator'
      fullPath: '/dashboard/coordinator'
      preLoaderRoute: typeof AuthenticatedDashboardCoordinatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/students': {
      id: '/_authenticated/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof AuthenticatedDashboardAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/projects': {
      id: '/_authenticated/dashboard/admin/projects'
      path: '/projects'
      fullPath: '/dashboard/admin/projects'
      preLoaderRoute: typeof AuthenticatedDashboardAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
  }
}

interface AuthenticatedDashboardAdminRouteChildren {
  AuthenticatedDashboardAdminProjectsRoute: typeof AuthenticatedDashboardAdminProjectsRoute
  AuthenticatedDashboardAdminStudentsRoute: typeof AuthenticatedDashboardAdminStudentsRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
}

const AuthenticatedDashboardAdminRouteChildren: AuthenticatedDashboardAdminRouteChildren =
  {
    AuthenticatedDashboardAdminProjectsRoute:
      AuthenticatedDashboardAdminProjectsRoute,
    AuthenticatedDashboardAdminStudentsRoute:
      AuthenticatedDashboardAdminStudentsRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
  }

const AuthenticatedDashboardAdminRouteWithChildren =
  AuthenticatedDashboardAdminRoute._addFileChildren(
    AuthenticatedDashboardAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedWeeklyUpdatesRoute: typeof AuthenticatedWeeklyUpdatesRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRouteWithChildren
  AuthenticatedDashboardCoordinatorRoute: typeof AuthenticatedDashboardCoordinatorRoute
  AuthenticatedDashboardStudentRoute: typeof AuthenticatedDashboardStudentRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedWeeklyUpdatesRoute: AuthenticatedWeeklyUpdatesRoute,
  AuthenticatedDashboardAdminRoute:
    AuthenticatedDashboardAdminRouteWithChildren,
  AuthenticatedDashboardCoordinatorRoute:
    AuthenticatedDashboardCoordinatorRoute,
  AuthenticatedDashboardStudentRoute: AuthenticatedDashboardStudentRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActividadesRoute: ActividadesRoute,
  ContactoRoute: ContactoRoute,
  IntegrantesRoute: IntegrantesRoute,
  LineasRoute: LineasRoute,
  LoginRoute: LoginRoute,
  ProyectosRoute: ProyectosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
