/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LineasRouteImport } from './routes/lineas'
import { Route as IntegrantesRouteImport } from './routes/integrantes'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWeeklyUpdatesRouteImport } from './routes/_authenticated/weekly-updates'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardStudentRouteImport } from './routes/_authenticated/dashboard.student'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardCoordinatorRouteImport } from './routes/_authenticated/dashboard.coordinator'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard.admin'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard.admin.index'
import { Route as AuthenticatedDashboardAdminUsersRouteImport } from './routes/_authenticated/dashboard.admin.users'
import { Route as AuthenticatedDashboardAdminUpdatesRouteImport } from './routes/_authenticated/dashboard.admin.updates'
import { Route as AuthenticatedDashboardAdminToolsRouteImport } from './routes/_authenticated/dashboard.admin.tools'
import { Route as AuthenticatedDashboardAdminTeamsRouteImport } from './routes/_authenticated/dashboard.admin.teams'
import { Route as AuthenticatedDashboardAdminStudentsRouteImport } from './routes/_authenticated/dashboard.admin.students'
import { Route as AuthenticatedDashboardAdminResourcesRouteImport } from './routes/_authenticated/dashboard.admin.resources'
import { Route as AuthenticatedDashboardAdminProjectsRouteImport } from './routes/_authenticated/dashboard.admin.projects'
import { Route as AuthenticatedDashboardAdminMeetingsRouteImport } from './routes/_authenticated/dashboard.admin.meetings'
import { Route as AuthenticatedDashboardAdminCompetitionsRouteImport } from './routes/_authenticated/dashboard.admin.competitions'
import { Route as AuthenticatedDashboardAdminActivitiesRouteImport } from './routes/_authenticated/dashboard.admin.activities'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LineasRoute = LineasRouteImport.update({
  id: '/lineas',
  path: '/lineas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrantesRoute = IntegrantesRouteImport.update({
  id: '/integrantes',
  path: '/integrantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWeeklyUpdatesRoute =
  AuthenticatedWeeklyUpdatesRouteImport.update({
    id: '/weekly-updates',
    path: '/weekly-updates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardStudentRoute =
  AuthenticatedDashboardStudentRouteImport.update({
    id: '/dashboard/student',
    path: '/dashboard/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCoordinatorRoute =
  AuthenticatedDashboardCoordinatorRouteImport.update({
    id: '/dashboard/coordinator',
    path: '/dashboard/coordinator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminUsersRoute =
  AuthenticatedDashboardAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminUpdatesRoute =
  AuthenticatedDashboardAdminUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminToolsRoute =
  AuthenticatedDashboardAdminToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminTeamsRoute =
  AuthenticatedDashboardAdminTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminStudentsRoute =
  AuthenticatedDashboardAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminResourcesRoute =
  AuthenticatedDashboardAdminResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminProjectsRoute =
  AuthenticatedDashboardAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminMeetingsRoute =
  AuthenticatedDashboardAdminMeetingsRouteImport.update({
    id: '/meetings',
    path: '/meetings',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminCompetitionsRoute =
  AuthenticatedDashboardAdminCompetitionsRouteImport.update({
    id: '/competitions',
    path: '/competitions',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminActivitiesRoute =
  AuthenticatedDashboardAdminActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/integrantes': typeof IntegrantesRoute
  '/lineas': typeof LineasRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre': typeof SobreRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/weekly-updates': typeof AuthenticatedWeeklyUpdatesRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/dashboard/coordinator': typeof AuthenticatedDashboardCoordinatorRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/activities': typeof AuthenticatedDashboardAdminActivitiesRoute
  '/dashboard/admin/competitions': typeof AuthenticatedDashboardAdminCompetitionsRoute
  '/dashboard/admin/meetings': typeof AuthenticatedDashboardAdminMeetingsRoute
  '/dashboard/admin/projects': typeof AuthenticatedDashboardAdminProjectsRoute
  '/dashboard/admin/resources': typeof AuthenticatedDashboardAdminResourcesRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/dashboard/admin/teams': typeof AuthenticatedDashboardAdminTeamsRoute
  '/dashboard/admin/tools': typeof AuthenticatedDashboardAdminToolsRoute
  '/dashboard/admin/updates': typeof AuthenticatedDashboardAdminUpdatesRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/integrantes': typeof IntegrantesRoute
  '/lineas': typeof LineasRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre': typeof SobreRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/weekly-updates': typeof AuthenticatedWeeklyUpdatesRoute
  '/dashboard/coordinator': typeof AuthenticatedDashboardCoordinatorRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/activities': typeof AuthenticatedDashboardAdminActivitiesRoute
  '/dashboard/admin/competitions': typeof AuthenticatedDashboardAdminCompetitionsRoute
  '/dashboard/admin/meetings': typeof AuthenticatedDashboardAdminMeetingsRoute
  '/dashboard/admin/projects': typeof AuthenticatedDashboardAdminProjectsRoute
  '/dashboard/admin/resources': typeof AuthenticatedDashboardAdminResourcesRoute
  '/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/dashboard/admin/teams': typeof AuthenticatedDashboardAdminTeamsRoute
  '/dashboard/admin/tools': typeof AuthenticatedDashboardAdminToolsRoute
  '/dashboard/admin/updates': typeof AuthenticatedDashboardAdminUpdatesRoute
  '/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/academy': typeof AcademyRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/integrantes': typeof IntegrantesRoute
  '/lineas': typeof LineasRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/weekly-updates': typeof AuthenticatedWeeklyUpdatesRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/_authenticated/dashboard/coordinator': typeof AuthenticatedDashboardCoordinatorRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/student': typeof AuthenticatedDashboardStudentRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/activities': typeof AuthenticatedDashboardAdminActivitiesRoute
  '/_authenticated/dashboard/admin/competitions': typeof AuthenticatedDashboardAdminCompetitionsRoute
  '/_authenticated/dashboard/admin/meetings': typeof AuthenticatedDashboardAdminMeetingsRoute
  '/_authenticated/dashboard/admin/projects': typeof AuthenticatedDashboardAdminProjectsRoute
  '/_authenticated/dashboard/admin/resources': typeof AuthenticatedDashboardAdminResourcesRoute
  '/_authenticated/dashboard/admin/students': typeof AuthenticatedDashboardAdminStudentsRoute
  '/_authenticated/dashboard/admin/teams': typeof AuthenticatedDashboardAdminTeamsRoute
  '/_authenticated/dashboard/admin/tools': typeof AuthenticatedDashboardAdminToolsRoute
  '/_authenticated/dashboard/admin/updates': typeof AuthenticatedDashboardAdminUpdatesRoute
  '/_authenticated/dashboard/admin/users': typeof AuthenticatedDashboardAdminUsersRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/actividades'
    | '/contacto'
    | '/integrantes'
    | '/lineas'
    | '/login'
    | '/proyectos'
    | '/sobre'
    | '/resources'
    | '/weekly-updates'
    | '/dashboard/admin'
    | '/dashboard/coordinator'
    | '/dashboard/settings'
    | '/dashboard/student'
    | '/dashboard/'
    | '/dashboard/admin/activities'
    | '/dashboard/admin/competitions'
    | '/dashboard/admin/meetings'
    | '/dashboard/admin/projects'
    | '/dashboard/admin/resources'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teams'
    | '/dashboard/admin/tools'
    | '/dashboard/admin/updates'
    | '/dashboard/admin/users'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/actividades'
    | '/contacto'
    | '/integrantes'
    | '/lineas'
    | '/login'
    | '/proyectos'
    | '/sobre'
    | '/resources'
    | '/weekly-updates'
    | '/dashboard/coordinator'
    | '/dashboard/settings'
    | '/dashboard/student'
    | '/dashboard'
    | '/dashboard/admin/activities'
    | '/dashboard/admin/competitions'
    | '/dashboard/admin/meetings'
    | '/dashboard/admin/projects'
    | '/dashboard/admin/resources'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teams'
    | '/dashboard/admin/tools'
    | '/dashboard/admin/updates'
    | '/dashboard/admin/users'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/academy'
    | '/actividades'
    | '/contacto'
    | '/integrantes'
    | '/lineas'
    | '/login'
    | '/proyectos'
    | '/sobre'
    | '/_authenticated/resources'
    | '/_authenticated/weekly-updates'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/coordinator'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/student'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/activities'
    | '/_authenticated/dashboard/admin/competitions'
    | '/_authenticated/dashboard/admin/meetings'
    | '/_authenticated/dashboard/admin/projects'
    | '/_authenticated/dashboard/admin/resources'
    | '/_authenticated/dashboard/admin/students'
    | '/_authenticated/dashboard/admin/teams'
    | '/_authenticated/dashboard/admin/tools'
    | '/_authenticated/dashboard/admin/updates'
    | '/_authenticated/dashboard/admin/users'
    | '/_authenticated/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcademyRoute: typeof AcademyRoute
  ActividadesRoute: typeof ActividadesRoute
  ContactoRoute: typeof ContactoRoute
  IntegrantesRoute: typeof IntegrantesRoute
  LineasRoute: typeof LineasRoute
  LoginRoute: typeof LoginRoute
  ProyectosRoute: typeof ProyectosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineas': {
      id: '/lineas'
      path: '/lineas'
      fullPath: '/lineas'
      preLoaderRoute: typeof LineasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrantes': {
      id: '/integrantes'
      path: '/integrantes'
      fullPath: '/integrantes'
      preLoaderRoute: typeof IntegrantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/weekly-updates': {
      id: '/_authenticated/weekly-updates'
      path: '/weekly-updates'
      fullPath: '/weekly-updates'
      preLoaderRoute: typeof AuthenticatedWeeklyUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/student': {
      id: '/_authenticated/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof AuthenticatedDashboardStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/coordinator': {
      id: '/_authenticated/dashboard/coordinator'
      path: '/dashboard/coordinator'
      fullPath: '/dashboard/coordinator'
      preLoaderRoute: typeof AuthenticatedDashboardCoordinatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/users': {
      id: '/_authenticated/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/updates': {
      id: '/_authenticated/dashboard/admin/updates'
      path: '/updates'
      fullPath: '/dashboard/admin/updates'
      preLoaderRoute: typeof AuthenticatedDashboardAdminUpdatesRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/tools': {
      id: '/_authenticated/dashboard/admin/tools'
      path: '/tools'
      fullPath: '/dashboard/admin/tools'
      preLoaderRoute: typeof AuthenticatedDashboardAdminToolsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/teams': {
      id: '/_authenticated/dashboard/admin/teams'
      path: '/teams'
      fullPath: '/dashboard/admin/teams'
      preLoaderRoute: typeof AuthenticatedDashboardAdminTeamsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/students': {
      id: '/_authenticated/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof AuthenticatedDashboardAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/resources': {
      id: '/_authenticated/dashboard/admin/resources'
      path: '/resources'
      fullPath: '/dashboard/admin/resources'
      preLoaderRoute: typeof AuthenticatedDashboardAdminResourcesRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/projects': {
      id: '/_authenticated/dashboard/admin/projects'
      path: '/projects'
      fullPath: '/dashboard/admin/projects'
      preLoaderRoute: typeof AuthenticatedDashboardAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/meetings': {
      id: '/_authenticated/dashboard/admin/meetings'
      path: '/meetings'
      fullPath: '/dashboard/admin/meetings'
      preLoaderRoute: typeof AuthenticatedDashboardAdminMeetingsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/competitions': {
      id: '/_authenticated/dashboard/admin/competitions'
      path: '/competitions'
      fullPath: '/dashboard/admin/competitions'
      preLoaderRoute: typeof AuthenticatedDashboardAdminCompetitionsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/activities': {
      id: '/_authenticated/dashboard/admin/activities'
      path: '/activities'
      fullPath: '/dashboard/admin/activities'
      preLoaderRoute: typeof AuthenticatedDashboardAdminActivitiesRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
  }
}

interface AuthenticatedDashboardAdminRouteChildren {
  AuthenticatedDashboardAdminActivitiesRoute: typeof AuthenticatedDashboardAdminActivitiesRoute
  AuthenticatedDashboardAdminCompetitionsRoute: typeof AuthenticatedDashboardAdminCompetitionsRoute
  AuthenticatedDashboardAdminMeetingsRoute: typeof AuthenticatedDashboardAdminMeetingsRoute
  AuthenticatedDashboardAdminProjectsRoute: typeof AuthenticatedDashboardAdminProjectsRoute
  AuthenticatedDashboardAdminResourcesRoute: typeof AuthenticatedDashboardAdminResourcesRoute
  AuthenticatedDashboardAdminStudentsRoute: typeof AuthenticatedDashboardAdminStudentsRoute
  AuthenticatedDashboardAdminTeamsRoute: typeof AuthenticatedDashboardAdminTeamsRoute
  AuthenticatedDashboardAdminToolsRoute: typeof AuthenticatedDashboardAdminToolsRoute
  AuthenticatedDashboardAdminUpdatesRoute: typeof AuthenticatedDashboardAdminUpdatesRoute
  AuthenticatedDashboardAdminUsersRoute: typeof AuthenticatedDashboardAdminUsersRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
}

const AuthenticatedDashboardAdminRouteChildren: AuthenticatedDashboardAdminRouteChildren =
  {
    AuthenticatedDashboardAdminActivitiesRoute:
      AuthenticatedDashboardAdminActivitiesRoute,
    AuthenticatedDashboardAdminCompetitionsRoute:
      AuthenticatedDashboardAdminCompetitionsRoute,
    AuthenticatedDashboardAdminMeetingsRoute:
      AuthenticatedDashboardAdminMeetingsRoute,
    AuthenticatedDashboardAdminProjectsRoute:
      AuthenticatedDashboardAdminProjectsRoute,
    AuthenticatedDashboardAdminResourcesRoute:
      AuthenticatedDashboardAdminResourcesRoute,
    AuthenticatedDashboardAdminStudentsRoute:
      AuthenticatedDashboardAdminStudentsRoute,
    AuthenticatedDashboardAdminTeamsRoute:
      AuthenticatedDashboardAdminTeamsRoute,
    AuthenticatedDashboardAdminToolsRoute:
      AuthenticatedDashboardAdminToolsRoute,
    AuthenticatedDashboardAdminUpdatesRoute:
      AuthenticatedDashboardAdminUpdatesRoute,
    AuthenticatedDashboardAdminUsersRoute:
      AuthenticatedDashboardAdminUsersRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
  }

const AuthenticatedDashboardAdminRouteWithChildren =
  AuthenticatedDashboardAdminRoute._addFileChildren(
    AuthenticatedDashboardAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedWeeklyUpdatesRoute: typeof AuthenticatedWeeklyUpdatesRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRouteWithChildren
  AuthenticatedDashboardCoordinatorRoute: typeof AuthenticatedDashboardCoordinatorRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardStudentRoute: typeof AuthenticatedDashboardStudentRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedWeeklyUpdatesRoute: AuthenticatedWeeklyUpdatesRoute,
  AuthenticatedDashboardAdminRoute:
    AuthenticatedDashboardAdminRouteWithChildren,
  AuthenticatedDashboardCoordinatorRoute:
    AuthenticatedDashboardCoordinatorRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardStudentRoute: AuthenticatedDashboardStudentRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcademyRoute: AcademyRoute,
  ActividadesRoute: ActividadesRoute,
  ContactoRoute: ContactoRoute,
  IntegrantesRoute: IntegrantesRoute,
  LineasRoute: LineasRoute,
  LoginRoute: LoginRoute,
  ProyectosRoute: ProyectosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
